baseurl: ""
url: ""
remote_theme: codeasashu/hcz-jekyll-blog
title: "Longern"
author: Longern
logo: https://longern.com/avatar.png
github: https://github.com/longern

include:
  - _nuxt

disqus_shortname: longern
google_analytics: UA-133314683-1

paginate: 6
