baseurl: https://gp.longern.com
remote_theme: codeasashu/hcz-jekyll-blog
title: "Longern"
author: Longern
logo: https://avatars1.githubusercontent.com/u/860892

include:
  - _nuxt

allowsearch: true

paginate: 6
